default: &default
  adapter: postgresql
  encoding: utf8
  template: template0
  pool: 5

development:
  <<: *default
  database: line_bot
  username: <%= ENV['USER'] %>
  password:

test:
  <<: *default
  database: line_bot_test
  username: <%= ENV['USER'] %>
  password:

staging:
  <<: *default
  database: line_bot_staging
  username: line_bot_root
  password: <%= ENV['PG_PASSWORD'] %>

production: &production
  <<: *default
  database: line_bot_production
  username: line_bot_root
  password: <%= ENV['PG_PASSWORD'] %>
